In [1]:
import numpy as np
import heuristics

In [2]:
np.random.seed(1)
n = 500
p = 10000
k = 10
X = np.random.randn(n,p)
beta = np.zeros(p)
beta[np.random.choice(p,k,replace=False)]=1
y = X@beta
beta_truth = np.copy(beta)

In [3]:
l0=28.
l2=0.1
M=1.
cost_truth = np.linalg.norm(y-X@beta_truth)**2+l0*np.sum(beta_truth!=0)+l2*np.sum(beta_truth**2)

In [4]:
beta1, cost1, _, support1 = heuristics.L0L2_ASCD_solve(X, y, l0, l2, M, upper_active_set_mask=None, S_diag=None, warm_start=None, \
                    cd_tol=1e-4, cd_max_itr=100, rel_tol=1e-6, kkt_max_itr=100, timing=False, maxtime=np.inf, verbose=True)

cost 280.99966828838495
280.99965107572183
iter 1
cost 280.99965107572183
no outliers, computing relative accuracy...


In [5]:
np.where(beta1)[0]

array([ 239,  304, 1048, 2119, 2186, 6501, 6866, 7301, 7544, 9967])

In [6]:
np.where(beta_truth)[0]

array([ 239,  304, 1048, 2119, 2186, 6501, 6866, 7301, 7544, 9967])

In [7]:
beta1[beta1!=0]

array([0.99976739, 0.99967986, 0.99966559, 0.99964781, 0.9995955 ,
       0.99956777, 0.99971882, 0.99963541, 0.99957282, 0.99959081])

In [8]:
cost1, cost_truth

(280.99965107572183, 281.0)

In [9]:
warm_start = {'beta':beta_truth, 'support':set(np.where(beta_truth)[0])}

beta2, cost2, _, support2 = heuristics.L0L2_ASCD_solve(X, y, l0, l2, M, upper_active_set_mask=None, S_diag=None, warm_start=warm_start, \
                    cd_tol=1e-4, cd_max_itr=100, rel_tol=1e-6, kkt_max_itr=100, timing=False, maxtime=np.inf, verbose=True)

cost 281.0
280.999652371465
iter 1
cost 280.999652371465
no outliers, computing relative accuracy...


In [10]:
l0_grid1,sols1= heuristics.fit_path_L0L2(X, y, lambda2 = 0.1, M = np.inf, solver='ASCD',
                  lambda0_grid = None, maxSuppSize = k,verbose=True)

L0L2 Heuristics Started.
491.00296963715516 0.1
Iteration: 0. Number of non-zeros:  1
392.8023757097242 0.1
Iteration: 1. Number of non-zeros:  2
314.24190056777934 0.1
Iteration: 2. Number of non-zeros:  3
251.39352045422348 0.1
Iteration: 3. Number of non-zeros:  4
201.1148163633788 0.1
Iteration: 4. Number of non-zeros:  10


/home/gridsan/wenyu/Research/NetworkPruning/Lagrangian-Heuristic/heuristics.py:281: RuntimeWarning: invalid value encountered in add
  criterion = np.where(np.abs(b)/2/(a+l2)<=M, b**2/4/(a+l2), -a*M**2+np.abs(b)*M-l2*M**2)


In [11]:
l0_grid2,sols2=heuristics.fit_path_L0L2(X, y, lambda2 = 0.1, M = np.inf, solver='ASCD',
                  lambda0_grid = np.logspace(2,3,10), maxSuppSize = k,verbose=True)

L0L2 Heuristics Started.
1000.0 0.1
Iteration: 0. Number of non-zeros:  0
774.263682681127 0.1
Iteration: 1. Number of non-zeros:  0
599.4842503189409 0.1
Iteration: 2. Number of non-zeros:  0
464.15888336127773 0.1
Iteration: 3. Number of non-zeros:  1
359.38136638046257 0.1
Iteration: 4. Number of non-zeros:  3
278.2559402207126 0.1
Iteration: 5. Number of non-zeros:  3
215.44346900318845 0.1
Iteration: 6. Number of non-zeros:  8
166.81005372000593 0.1
Iteration: 7. Number of non-zeros:  10
